version: "3.7"
services:
  nginx:
    container_name: nginx
    image: alfg/nginx-rtmp
    ports:
      - '8080:80' # local port:container port
      - '1935:1935' # local port:container port
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf.template' # local path:container path
